
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author juangonzalezcalleros
 */
public class CalculoInteres extends javax.swing.JFrame {

    /**
     * Creates new form CalculoInteres
     */
    public CalculoInteres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Principal");

        jLabel2.setText("Years");

        jLabel3.setText("rate");

        jButton1.setText("Calcular Interes Compuesto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String principalString = jTextField1.getText();
        String yearsString = jTextField2.getText();
        String rateString = jTextField3.getText();
        
        double principal, rate, years;
        
        principal = Double.parseDouble(principalString);
        years = Double.parseDouble(yearsString);
        rate = Double.parseDouble(rateString); 
        rate = rate/100.0;
        
        DecimalFormat precisionTwo = new DecimalFormat( "0.00" );
        JTextArea outputTextArea = new JTextArea( 11, 20 );
        
        outputTextArea.append( "Year\tAmount on deposit\n" );
        String out="Year\tAmount on deposit\n";
        
        
        double amount = 0.0;
        for ( int year = 1; year <= years; year++ ) {
            amount = principal * Math.pow( 1.0 + rate, year );
            outputTextArea.append( year + "\t" +
            precisionTwo.format( amount ) + "\n" );    
            out = out+ year + "\t" +
            precisionTwo.format( amount ) + "\n";
            
        }
        /*
        int opcion =-1;
        
        switch (opcion){
            case 1:
                JOptionPane.showMessageDialog(
                null, outputTextArea, "Compound Interest",
                JOptionPane.INFORMATION_MESSAGE ); 
                

            case 2:
                JOptionPane.showMessageDialog(
                null, out, "Compound Interest",
                JOptionPane.INFORMATION_MESSAGE );        
                

            default: 
                JOptionPane.showMessageDialog(
                null, "Quizás no quieres imprimir el resultado, selecciona 1 o 2", "Compound Interest",
                JOptionPane.INFORMATION_MESSAGE );                        
        } 
        
        
        */
        
        
        int edad=18;
        String age ="18";
        
        switch (edad){
            case 18: 
                JOptionPane.showMessageDialog (null, "Eres mayor de edad y debes votar"); 
                break;
            case 17: 
                JOptionPane.showMessageDialog (null, "Ya casi eres mayor de edad tramita tu credencial de votar");
                break;
            case 16: 
                JOptionPane.showMessageDialog (null, "Aún eres jovén integrate a los dialogos con los jóvenes");
                break;
                
            default:
                JOptionPane.showMessageDialog (null, "tu edad esta fuera del rango de mis mensajes"); 
        }
        
        
        
        int calificacion; //1 era aprobado y 2 reprobado
        String valor;
        
        do{
            valor = JOptionPane.showInputDialog("Ingresa 1 para aprobado o 2 para reprobado");
            calificacion = Integer.parseInt (valor);
                } while (calificacion != 1 && calificacion !=2);
        
                
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculoInteres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculoInteres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculoInteres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculoInteres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculoInteres().setVisible(true);
            }
        });
    }

    /*
        jLabel1 corresponde a la etiqueta Principal
        jLabel2 corresponde a la etiqueta years
        jLabel3 corresponde a la etiqueta rate
        jTextfield1 corresponde a la etiqueta Principal
        jTextfield2 corresponde a la etiqueta years
        jTextfield3 corresponde a la etiqueta rate
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
